
environment:
    nodejs_version: "6"
    
install:
    # Setup rust to cross-compile for 64bit linux
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -y --default-toolchain stable --default-host x86_64-pc-windows-gnu
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - rustc -vV
    - cargo -vV
    # Install node and node modules for statsbot and balancebot
    - ps: Install-Product node $env:nodejs_version
    - cd statsbot
    - npm install --depth 0 --silent
    - cd ../balancebot
    - npm install --depth 0 --silent
    - cd ..
    
# Install our own version of node, so this isn't important
image: Visual Studio 2015

build_script:
    # Build statsbot
    - cd statsbot
    - npm run build
    # Build balancebot
    - cd ../balancebot
    - npm run build
    - cd ..
    # Build artifacts
    - tar czf stats-lib.tar.gz stats-lib
    - cat statsbot/statsbot.min.js | gzip --best > statsbot.min.js.gz
    - cat balancebot/balancebot.min.js | gzip --best > balancebot.min.js.gz
    
test_script:
    - cd stats-lib-rs
    - cargo test
    - cd ..
    
artifacts:
    - path: statsbot.min.js.gz
    - path: balancebot.min.js.gz
    - path: stats-lib.tar.gz
