
environment:
    nodejs_version: "6"
    
install:
    - ps: Install-Product node $env:nodejs_version
    - cd statsbot
    - npm install --depth 0 --quiet
    - cd ../balancebot
    - npm install --depth 0 --quiet
    - cd ..
    
# Install our own version of node, so this isn't important
image: Visual Studio 2015

build_script:
    - cd statsbot
    - npm run build
    - cd ..
    - tar czf stats-lib.tar.gz stats-lib
    - cat statsbot/statsbot.min.js | gzip --best > statsbot.min.js.gz
    
artifacts:
    - path: statsbot.min.js.gz
    - path: stats-lib.tar.gz
