
environment:
    nodejs_version: "6"
    
install:
    - ps: Install-Product node $env:nodejs_version
    - cd statsbot
    - npm install --depth 0
    - cd ..
    
# Install our own version of node, so this isn't important
image: Visual Studio 2015

build_script:
    - cd statsbot
    - npm run build
    - cd ..
    - tar czf stats-lib.tar.gz stats-lib
    
artifacts:
    - path: statsbot/statsbot.min.js
    - path: stats-lib.tar.gz
