
environment:
    nodejs_version: "6"
    
install:
   python -m pip install -U sphinx
    
# Install our own version of node, so this isn't important
image: Visual Studio 2015

build_script:
    # Build artifacts
    - cd docs
    - make singlehtml
    - cd build
    - 7z a docs.zip singlehtml
    - mv docs.zip ../../docs.zip
    
artifacts:
    - path: startup
    - path: docs.zip
