# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        working_directory: ~/repo
    
        docker:
            - image: abronan/rust-circleci:latest
        steps:
            - checkout
            - run:
                command: |
                    cd ~/repo/stats-lib-rs
                    rustup run stable cargo build --release
            - store_artifacts:
                path: ~/repo/stats-lib-rs/target/release/anonymise
                destination: /anonymise

    test:
        working_directory: ~/repo
    
        docker:
            - image: abronan/rust-circleci:latest
        steps:
            - checkout
            - run:
                command: |
                    cd ~/repo/stats-lib-rs
                    rustup run stable cargo test
                    
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build
